### ISSUE TITLE
Broken Samples Link in English Documentation

### ISSUE THREAD

**Issue by lucasalavapena** [AndyClifton/accessibility#46]
The link to [accessibility/samples](https://github.com/AndyClifton/accessibility/samples), in section 5 of the English documentation (both on CTAN and [this repo](https://github.com/AndyClifton/accessibility/blob/master/source/v2x/accessibility.pdf)),  results in a 404 error page.

**Comment by AndyClifton** [comment]
Fixed. Sorry about that!
