### ISSUE TITLE
Zoom TeX Hour on accessible mathematics (details in thread)

### ISSUE THREAD

**Issue by AndyClifton** [AndyClifton/accessibility#47]
From @jfine2358 and raised in #42, now mentioned here for visibility:

> Perhaps off-topic. I'm holding a zoom TeX Hour on accessible mathematics, on Thursday 11 January (6:30 to 7:30pm). All are welcome. For the zoom info see https://jfine2358.github.io/contact/. I've emailed @AndyClifton  providing more information.
>
> Also relevant is https://jfine2358.github.io/post/2021/01/21/blind-math-news/."

_Originally posted by @jfine2358 in https://github.com/AndyClifton/accessibility/issues/42#issuecomment-775881017_

**Comment by AndyClifton** [comment]
@jfine2358. Did you mean 11 January or February?

**Comment by jfine2358** [comment]
I meant Thursday 11 February. In other words the day after tomorrow! Thank you for giving this event additional visibility. Note that the meeting is at 6:30 to 7:30pm UK time.

The time right now the UK is https://www.google.com/search?q=uk+time.

**Comment by AndyClifton** [comment]
Event has now passed.

**Comment by ivanistheone** [comment]
> Event has now passed.

For recording of the event, see https://www.youtube.com/watch?v=VJWndkDema4
